In [86]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
import streamlit as st
import joblib

In [7]:
df = pd.read_csv('heart_disease.csv')

In [9]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,diagnosis,target
0,63,1,1,145.0,233.0,1,2,150,0,2.3,3,1.0,6.0,0,0
1,67,1,4,160.0,286.0,0,2,108,1,1.5,2,3.0,3.0,2,1
2,67,1,4,120.0,229.0,0,2,129,1,2.6,2,2.0,7.0,1,1
3,37,1,3,130.0,250.0,0,0,187,0,3.5,3,1.0,3.0,0,0
4,41,0,2,130.0,204.0,0,2,172,0,1.4,1,1.0,3.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110.0,264.0,0,0,132,0,1.2,2,1.0,7.0,1,1
299,68,1,4,144.0,193.0,1,0,141,0,3.4,2,2.0,7.0,2,1
300,57,1,4,130.0,131.0,0,0,115,1,1.2,2,1.0,7.0,3,1
301,57,0,2,130.0,236.0,0,2,174,0,0.0,2,1.0,3.0,1,1
302,38,1,3,138.0,175.0,0,0,173,0,0.0,1,1.0,3.0,0,0

In [11]:
X = df.drop([" diagnosis", "target"], axis=1)  
y = df["target"]                               

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [13]:
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145.0,233.0,1,2,150,0,2.3,3,1.0,6.0
1,67,1,4,160.0,286.0,0,2,108,1,1.5,2,3.0,3.0
2,67,1,4,120.0,229.0,0,2,129,1,2.6,2,2.0,7.0
3,37,1,3,130.0,250.0,0,0,187,0,3.5,3,1.0,3.0
4,41,0,2,130.0,204.0,0,2,172,0,1.4,1,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110.0,264.0,0,0,132,0,1.2,2,1.0,7.0
299,68,1,4,144.0,193.0,1,0,141,0,3.4,2,2.0,7.0
300,57,1,4,130.0,131.0,0,0,115,1,1.2,2,1.0,7.0
301,57,0,2,130.0,236.0,0,2,174,0,0.0,2,1.0,3.0
302,38,1,3,138.0,175.0,0,0,173,0,0.0,1,1.0,3.0

In [15]:
y

0      0
1      1
2      1
3      0
4      0
      ..
298    1
299    1
300    1
301    1
302    0
Name: target, Length: 303, dtype: int64

In [17]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
selector = SelectKBest(score_func=f_classif, k=8)
X_new = selector.fit_transform(X, y)
print("Selected features:", X.columns[selector.get_support()])

Selected features: Index([' sex', ' cp', ' thalach', ' exang', ' oldpeak', ' slope', ' ca',
       ' thal'],
      dtype='object')

In [21]:
model = LogisticRegression()
scores = cross_val_score(model, X_train_scaled, y_train, cv=5)
print("CV Accuracy:", scores.mean())

CV Accuracy: 0.8013605442176871

#
supervised model
#

-------------------------

classification   
use classification model beacause data is categorical

Logistic Regression

In [30]:
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_scaled, y_train)

y_pred = log_reg.predict(X_test_scaled)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Logistic Regression Accuracy: 0.8524590163934426
              precision    recall  f1-score   support

           0       0.90      0.82      0.86        33
           1       0.81      0.89      0.85        28

    accuracy                           0.85        61
   macro avg       0.85      0.86      0.85        61
weighted avg       0.86      0.85      0.85        61

Random Forest

svm model

In [39]:
svm = SVC(kernel='rbf', probability=True)
svm.fit(X_train_scaled, y_train)

y_pred = svm.predict(X_test_scaled)

print("SVM Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

SVM Accuracy: 0.8688524590163934
              precision    recall  f1-score   support

           0       0.90      0.85      0.88        33
           1       0.83      0.89      0.86        28

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.87      0.87      0.87        61

K-Nearest Neighbors (KNN)

In [45]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

y_pred = knn.predict(X_test_scaled)

print("KNN Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

KNN Accuracy: 0.8360655737704918
              precision    recall  f1-score   support

           0       0.90      0.79      0.84        33
           1       0.78      0.89      0.83        28

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

In [35]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train_scaled, y_train)

y_pred = rf.predict(X_test_scaled)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Random Forest Accuracy: 0.8688524590163934
              precision    recall  f1-score   support

           0       0.90      0.85      0.88        33
           1       0.83      0.89      0.86        28

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.87      0.87      0.87        61

In [51]:
joblib.dump(rf, "model/final_model.pkl")
joblib.dump(scaler, "model/scaler.pkl")

print("✅ Model and scaler saved in models/ folder")

✅ Model and scaler saved in models/ folder

In [71]:
app_code = """
import streamlit as st
import pandas as pd
import joblib

# Load model and scaler
model = joblib.load("model/final_model.pkl")
scaler = joblib.load("model/scaler.pkl")

st.title("Heart Disease Prediction 🫀")

st.write("Enter patient data to predict heart disease:")

# User inputs
age = st.number_input("Age", 20, 100, 50)
sex = st.selectbox("Sex", [0, 1])  
cp = st.selectbox("Chest Pain Type (cp)", [0, 1, 2, 3])
trestbps = st.number_input("Resting Blood Pressure", 80, 200, 120)
chol = st.number_input("Cholesterol", 100, 600, 200)
fbs = st.selectbox("Fasting Blood Sugar > 120 mg/dl", [0, 1])
restecg = st.selectbox("Resting ECG", [0, 1, 2])
thalach = st.number_input("Max Heart Rate Achieved", 60, 250, 150)
exang = st.selectbox("Exercise Induced Angina", [0, 1])
oldpeak = st.number_input("ST Depression", 0.0, 6.0, 1.0, step=0.1)
slope = st.selectbox("Slope of ST Segment", [0, 1, 2])
ca = st.selectbox("Number of Major Vessels (0-3)", [0, 1, 2, 3])
thal = st.selectbox("Thalassemia", [0, 1, 2, 3])

# Build dataframe with same column names as training
input_data = pd.DataFrame([[age, sex, cp, trestbps, chol, fbs, restecg,
                            thalach, exang, oldpeak, slope, ca, thal]],
                          columns=['age', ' sex', ' cp', ' trestbps', ' chol', ' fbs',
                                   ' restecg', ' thalach', ' exang', ' oldpeak',
                                   ' slope', ' ca', ' thal'])

# Convert to float
input_data = input_data.astype(float)

# Scale data
X_scaled = scaler.transform(input_data)

# Prediction
if st.button("Predict"):
    prediction = model.predict(X_scaled)
    if prediction[0] == 1:
        st.error("⚠️ The patient is likely to have heart disease")
    else:
        st.success("✅ The patient is healthy (no heart disease)")
"""

with open("heart_app.py", "w", encoding="utf-8") as f:
    f.write(app_code)

print("✅ Streamlit app saved as heart_app.py. Run it with: streamlit run heart_app.py")

✅ Streamlit app saved as heart_app.py. Run it with: streamlit run heart_app.py